### Registro de Usuarios
POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "cristian",
    "email": "cristian@mail.com",
    "password": "cristian54321",
    "c_password": "cristian54321"
}

### Autenticación (login)

POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "juan@mail.com",
    "password": "juan54321"
}

### Perfil

GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 7|UJQDiU1rWEZSjRqLwONjowrm9cUsHUJbYPzQMkmN218119b3


### Salir
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 8|nM8QIXQNGJY6P9L1E4IA5p9jUXNP77BlzfUoC9Ij26aec0be

### resent verification email
GET http://127.0.0.1:8000/api/email/resend
Accept: application/json
Authorization: Bearer 12|gSADUVQK4G5019LDnnSJG8oWZFnxaWTOu4z3qleq390380ec
