### plan
GET http://127.0.0.1:8000/api/plan
Accept: application/json
Content-Type: application/json


### programa
GET http://127.0.0.1:8000/api/programa/1
Accept: application/json
Content-Type: application/json


### modifocacion problematica
POST   http://127.0.0.1:8000/api/modificar-transferencia/73
Accept: application/json
Content-Type: application/json

{
    "nombre_tpp": "pedroppppppppppppppppppppppppppppppppp",
    "objeto": "transferencia modificado",
    "localizacion": "localizacion modificado",
    "denominacion_convenio": "nombre original modificadoooooooooooooooooooooooooo",
    "fecha_inicio": "25/08/2024",
    "fecha_termino": "28/08/2024",
    "area_id": 1,
    "entidad_operadora_id": 1,
    "entidad_ejecutora": "MMMMMMM",
    "id": 58
}

### guardar problematica
POST   http://127.0.0.1:8000/api/guardar-problematica/58
Accept: application/json
Content-Type: application/json

{
    "plan_id": 1,
    "programa_id": 1,
    "descripcion": "problematica"
}


### guardar localizazion
POST   http://127.0.0.1:8000/api/guardar-localizacion/58
Accept: application/json
Content-Type: application/json

{
    "departamento_id": 1,
    "municipio_id": 1,
    "poblacion_id": 1,
    "cobertura": 1,
    "poblacion": 1
}


### Activar cierre
GET http://127.0.0.1:8000/api/activar-cierre/89
Accept: application/json
Content-Type: application/json

### cierre formulario
GET http://127.0.0.1:8000/api/cierre-formulario/93
Accept: application/json
Content-Type: application/json



### departamento
GET http://127.0.0.1:8000/api/departamento
Accept: application/json
Content-Type: application/json


### municipio
GET http://127.0.0.1:8000/api/municipio
Accept: application/json
Content-Type: application/json


### municipio
GET http://127.0.0.1:8000/api/municipio/2
Accept: application/json
Content-Type: application/json


### poblacion
GET http://127.0.0.1:8000/api/poblacion
Accept: application/json
Content-Type: application/json

### poblacion
GET http://127.0.0.1:8000/api/poblacion/1
Accept: application/json
Content-Type: application/json

### listar transferencia
GET http://127.0.0.1:8000/api/listar-transferencia/2
Accept: application/json
Content-Type: application/json


### listar formulario
GET http://127.0.0.1:8000/api/dictamen-listar/94
Accept: application/json
Content-Type: application/json

### listar formulario
GET http://127.0.0.1:8000/api/dictamen-eliminar/25
Accept: application/json
Content-Type: application/json


### mostrar formulario
GET http://127.0.0.1:8000/api/dictamen-mostrar/7
Accept: application/json
Content-Type: application/json

### listar tipo dictamen
GET http://127.0.0.1:8000/api/listar-tipo
Accept: application/json
Content-Type: application/json

### guardar formulario
POST  http://127.0.0.1:8000/api/guardar-dictamen/68
Accept: application/json
Content-Type: application/json

{
    "fecha_registro": "24/09/2024",
    "fecha_inicio": "24/09/2024",
    "fecha_termino": "24/09/2024",
    "etapa": 1,
    "pregunta_1": true,
    "pregunta_2": true,  
    "pregunta_3": true,
    "respaldo_pregunta_3": "pregunta 3",
    "fecha_pregunta_3": "24/09/2024",
    "pregunta_4": true,
    "respaldo_pregunta_4": "pregunta 4",
    "fecha_pregunta_4": "24/09/2024",
    "pregunta_5": true,
    "respaldo_pregunta_5": "pregunta 5",
    "fecha_pregunta_5": "24/09/2024",
    "pregunta_6": true,
    "respaldo_pregunta_6": "pregunta 6",
    "fecha_pregunta_6": "24/09/2024",
    "mae": "nombre mae",
    "mae_cargo": "cargo mae",
    "mae_ci": "ci mae",
    "mae_documento_designacion":"doc designacion",
    "responsable": "Responsable",
    "responsable_ci": "4545545",
    "responsable_cargo": "responsable cargo",
    "responsable_unidad": "Responsable unidad"
}


### modificiar formulario
POST  http://127.0.0.1:8000/api/modificar-dictamen/94
Accept: application/json
Content-Type: application/json

{
    "fecha_registro": "10/10/2024",
    "fecha_inicio": "24/09/2024",
    "fecha_termino": "24/09/2024",
    "etapa": 1,
    "pregunta_1": true,
    "pregunta_2": true,  
    "pregunta_3": true,
    "respaldo_pregunta_3": "AAAAAAAAA",
    "fecha_pregunta_3": "24/09/2024",
    "pregunta_4": true,
    "respaldo_pregunta_4": "BBBBBBB",
    "fecha_pregunta_4": "24/09/2024",
    "pregunta_5": true,
    "respaldo_pregunta_5": "pregunta 55555",
    "fecha_pregunta_5": "24/09/2024",
    "pregunta_6": true,
    "respaldo_pregunta_6": "pregunta 66666",
    "fecha_pregunta_6": "24/09/2024",
    "mae": "nombre mae",
    "mae_cargo": "cargo mae",
    "mae_ci": "111111111",
    "mae_documento_designacion":"mae",
    "responsable": "Responsable",
    "responsable_ci": "4545545",
    "responsable_cargo": "responsable cargo",
    "responsable_unidad": "Responsable unidad"
}
