### plan
GET http://127.0.0.1:8000/api/plan
Accept: application/json
Content-Type: application/json


### programa
GET http://127.0.0.1:8000/api/programa/1
Accept: application/json
Content-Type: application/json


### modifocacion problematica
POST   http://127.0.0.1:8000/api/modificar-transferencia/58
Accept: application/json
Content-Type: application/json

{
    "nombre_tpp": "pedroppppppppppppppppppppppppppppppppp",
    "objeto": "transferencia modificado",
    "localizacion": "localizacion modificado",
    "denominacion_convenio": "nombre original modificadoooooooooooooooooooooooooo",
    "fecha_inicio": "25/08/2024",
    "fecha_termino": "28/08/2024",
    "id_area": 1,
    "entidad_operadora": "pedro54321",
    "id": 58
}

### guardar problematica
POST   http://127.0.0.1:8000/api/guardar-problematica/58
Accept: application/json
Content-Type: application/json

{
    "plan_id": 1,
    "programa_id": 1,
    "descripcion": "problematica"
}


### guardar localizazion
POST   http://127.0.0.1:8000/api/guardar-localizacion/58
Accept: application/json
Content-Type: application/json

{
    "departamento_id": 1,
    "municipio_id": 1,
    "poblacion_id": 1,
    "cobertura": 1,
    "poblacion": 1
}






### departamento
GET http://127.0.0.1:8000/api/departamento
Accept: application/json
Content-Type: application/json


### municipio
GET http://127.0.0.1:8000/api/municipio
Accept: application/json
Content-Type: application/json


### municipio
GET http://127.0.0.1:8000/api/municipio/2
Accept: application/json
Content-Type: application/json


### poblacion
GET http://127.0.0.1:8000/api/poblacion
Accept: application/json
Content-Type: application/json

### poblacion
GET http://127.0.0.1:8000/api/poblacion/1
Accept: application/json
Content-Type: application/json