POST http://127.0.0.1:8000/api/reset-password
Content-Type: application/json
Accept: application/json

{
    "email": "admin@mail.com"
}

### cambio de contraseña
POST http://127.0.0.1:8000/api/change-password
Content-Type: application/json
Accept: application/json

{
    "token": "c67bebbf703afa8ac4489aa88121ef5359991aa5bea6e5ebc7ada6dee4f61b9d",
    "email": "admin@mail.com",
    "password": "admin54321",
    "password_confirmation": "admin54321"
}